development:
  adapter: postgresql
  encoding: unicode
  database: diamonds
  pool: 5
  username: nirnaori
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: diamonds
  pool: 5
  username: nirnaori
  password:


